### ISSUE TITLE
FIle is not a zip file

### ISSUE THREAD

**Issue by ridwanulhoquejr** [Kowsher/Bangl-Fasttext#2]
![image](https://user-images.githubusercontent.com/52696988/189579641-00b751fd-50a0-47be-9b77-7f41aad10d2a.png)

**Comment by shohanursobuj** [comment]
You must manually download the URL using gdown because the PyPI package was unable to do so because the link had expired.  
Here is a sample of the code. I've included the notebook file in a compressed format as well.
![banglaFastText_download_issues](https://user-images.githubusercontent.com/46314163/192007044-80a6d019-5238-4e35-9234-863b8b9eee83.png)

**N.B.** Use a minimum of 16GB of RAM. Google Collab will crash when the model is loaded.

**Attachment:** [BanglaFastText_issue.zip](https://github.com/Kowsher/Bangla-Fasttext/files/9635371/BanglaFastText_issue.zip)
